
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config.Runtime;
using SimpleJSON;

namespace Hotfix.Config.ai
{
    public sealed partial class ExecuteTimeStatistic : ai.Service
    {
        public ExecuteTimeStatistic(JSONNode _buf) : base(_buf) 
        {
            PostInit();
        }

        public static ExecuteTimeStatistic DeserializeExecuteTimeStatistic(JSONNode _buf)
        {
            return new ai.ExecuteTimeStatistic(_buf);
        }

        public const int __ID__ = 990693812;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef(TablesComponent tables)
        {
            base.ResolveRef(tables);
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "nodeName:" + NodeName + ","
            + "}";
        }

        partial void PostInit();
    }
}
