
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config.ai
{
    public sealed partial class IsSet2 : ai.KeyQueryOperator
    {
        public IsSet2(JSONNode _buf) : base(_buf) 
        {
            PostInit();
        }

        public static IsSet2 DeserializeIsSet2(JSONNode _buf)
        {
            return new ai.IsSet2(_buf);
        }

        public const int __ID__ = -843729664;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef(TablesComponent tables)
        {
            base.ResolveRef(tables);
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
    }
}
