
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config.Runtime;
using SimpleJSON;

namespace Hotfix.Config.ai
{
    public sealed partial class KeepFaceTarget : ai.Service
    {
        public KeepFaceTarget(JSONNode _buf) : base(_buf) 
        {
            { if(!_buf["target_actor_key"].IsString) { throw new SerializationException(); }  TargetActorKey = _buf["target_actor_key"]; }
            PostInit();
        }

        public static KeepFaceTarget DeserializeKeepFaceTarget(JSONNode _buf)
        {
            return new ai.KeepFaceTarget(_buf);
        }

        public readonly string TargetActorKey;
        public const int __ID__ = 1195270745;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef(TablesComponent tables)
        {
            base.ResolveRef(tables);
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "nodeName:" + NodeName + ","
            + "targetActorKey:" + TargetActorKey + ","
            + "}";
        }

        partial void PostInit();
    }
}
