
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config.Runtime;
using SimpleJSON;

namespace Hotfix.Config.ai
{
    public abstract partial class Task : ai.FlowNode
    {
        public Task(JSONNode _buf) : base(_buf) 
        {
            { if(!_buf["ignore_restart_self"].IsBoolean) { throw new SerializationException(); }  IgnoreRestartSelf = _buf["ignore_restart_self"]; }
            PostInit();
        }

        public static Task DeserializeTask(JSONNode _buf)
        {
            switch ((string)_buf["$type"])
            {
                case "UeWait": return new ai.UeWait(_buf);
                case "UeWaitBlackboardTime": return new ai.UeWaitBlackboardTime(_buf);
                case "MoveToTarget": return new ai.MoveToTarget(_buf);
                case "ChooseSkill": return new ai.ChooseSkill(_buf);
                case "MoveToRandomLocation": return new ai.MoveToRandomLocation(_buf);
                case "MoveToLocation": return new ai.MoveToLocation(_buf);
                case "DebugPrint": return new ai.DebugPrint(_buf);
                default: throw new SerializationException();
            }
        }

        public readonly bool IgnoreRestartSelf;

        public override void ResolveRef(TablesComponent tables)
        {
            base.ResolveRef(tables);
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "nodeName:" + NodeName + ","
            + "decorators:" + StringUtil.CollectionToString(Decorators) + ","
            + "services:" + StringUtil.CollectionToString(Services) + ","
            + "ignoreRestartSelf:" + IgnoreRestartSelf + ","
            + "}";
        }

        partial void PostInit();
    }
}
