
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config.Runtime;
using GameFrameX.Config.Runtime;
using SimpleJSON;


namespace Hotfix.Config.common
{
    public partial class TbGlobalConfig : BaseDataTable<common.GlobalConfig>
    {
    
        private common.GlobalConfig _data;
        public common.GlobalConfig Data => _data;
        private readonly System.Func<System.Threading.Tasks.Task<JSONNode>> _loadFunc;
    
        public TbGlobalConfig(System.Func<System.Threading.Tasks.Task<JSONNode>> loadFunc)
        {
            _loadFunc = loadFunc;
        }
    
        public override async System.Threading.Tasks.Task LoadAsync()
        {
            JSONNode _json = await _loadFunc();
            int n = _json.Count;
            if (n != 1) throw new SerializationException("table mode=one, but size != 1");
            { if(!_json[0].IsObject) { throw new SerializationException(); }  _data = common.GlobalConfig.DeserializeGlobalConfig(_json[0]);  }
        }
    
        /// <summary>
        /// 背包容量
        /// </summary>
        public int X1 => _data.X1;
        public int X2 => _data.X2;
        public int X3 => _data.X3;
        public int X4 => _data.X4;
        public int X5 => _data.X5;
        public int X6 => _data.X6;
        public System.Collections.Generic.List<int> X7 => _data.X7;
    
        public void ResolveRef(TablesComponent tables)
        {
            _data.ResolveRef(tables);
        }
    
        partial void PostInit();
    }
}

