
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config
{
    /// <summary>
    /// 取两个值的范围:<br/>1,3 就相当于[1,3)
    /// </summary>
    public sealed partial class RangeTowNumber : LuBan.Runtime.BeanBase
    {
        public RangeTowNumber(int Range1, int Range2) 
        {
            this.Range1 = Range1;
            this.Range2 = Range2;
            PostInit();
        }

        public RangeTowNumber(JSONNode _buf)
        {
            { if(!_buf["range_1"].IsNumber) { throw new SerializationException(); }  Range1 = _buf["range_1"]; }
            { if(!_buf["range_2"].IsNumber) { throw new SerializationException(); }  Range2 = _buf["range_2"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static RangeTowNumber DeserializeRangeTowNumber(JSONNode _buf)
        {
            return new RangeTowNumber(_buf);
        }

        /// <summary>
        /// 范围1
        /// </summary>
        public int Range1 { private set; get; }
        /// <summary>
        /// 范围2
        /// </summary>
        public int Range2 { private set; get; }
        public const int __ID__ = 601676584;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "range1:" + Range1 + ","
            + "range2:" + Range2 + ","
            + "}";
        }

        partial void PostInit();
    }
}
