
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config
{
    /// <summary>
    /// 用于资源在游戏内的名字展示,以及资源在目录下的资产名称
    /// </summary>
    public sealed partial class ResourceCKBean : LuBan.Runtime.BeanBase
    {
        public ResourceCKBean(string Content, string FileName) 
        {
            this.Content = Content;
            this.FileName = FileName;
            PostInit();
        }

        public ResourceCKBean(JSONNode _buf)
        {
            { if(!_buf["content"].IsString) { throw new SerializationException(); }  Content = _buf["content"]; }
            { if(!_buf["file_name"].IsString) { throw new SerializationException(); }  FileName = _buf["file_name"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static ResourceCKBean DeserializeResourceCKBean(JSONNode _buf)
        {
            return new ResourceCKBean(_buf);
        }

        /// <summary>
        /// 名字
        /// </summary>
        public string Content { private set; get; }
        /// <summary>
        /// 对应资源的文件名
        /// </summary>
        public string FileName { private set; get; }
        public const int __ID__ = -1539577370;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "content:" + Content + ","
            + "fileName:" + FileName + ","
            + "}";
        }

        partial void PostInit();
    }
}
