
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config
{
    /// <summary>
    /// 用于设置多立绘的位置和资源获取
    /// </summary>
    public sealed partial class ShowPositionAndResId : LuBan.Runtime.BeanBase
    {
        public ShowPositionAndResId(res.ShowPostion PaintingPostion, string ResId) 
        {
            this.PaintingPostion = PaintingPostion;
            this.ResId = ResId;
            PostInit();
        }

        public ShowPositionAndResId(JSONNode _buf)
        {
            { if(!_buf["painting_postion"].IsNumber) { throw new SerializationException(); }  PaintingPostion = (res.ShowPostion)_buf["painting_postion"].AsInt; }
            { if(!_buf["res_id"].IsString) { throw new SerializationException(); }  ResId = _buf["res_id"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static ShowPositionAndResId DeserializeShowPositionAndResId(JSONNode _buf)
        {
            return new ShowPositionAndResId(_buf);
        }

        /// <summary>
        /// 立绘位置
        /// </summary>
        public res.ShowPostion PaintingPostion { private set; get; }
        /// <summary>
        /// 资源ID
        /// </summary>
        public string ResId { private set; get; }
        public const int __ID__ = 419216330;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "paintingPostion:" + PaintingPostion + ","
            + "resId:" + ResId + ","
            + "}";
        }

        partial void PostInit();
    }
}
