
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config
{
    /// <summary>
    /// 用于设置剧情的前置条件配置
    /// </summary>
    public sealed partial class StoryCondition : LuBan.Runtime.BeanBase
    {
        public StoryCondition(int StoryId, story.ConditionType Type, System.Collections.Generic.List<int> Condition) 
        {
            this.StoryId = StoryId;
            this.Type = Type;
            this.Condition = Condition;
            PostInit();
        }

        public StoryCondition(JSONNode _buf)
        {
            { if(!_buf["StoryId"].IsNumber) { throw new SerializationException(); }  StoryId = _buf["StoryId"]; }
            { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = (story.ConditionType)_buf["Type"].AsInt; }
            { var __json0 = _buf["Condition"]; if(!__json0.IsArray) { throw new SerializationException(); } Condition = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Condition.Add(__v0); }   }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static StoryCondition DeserializeStoryCondition(JSONNode _buf)
        {
            return new StoryCondition(_buf);
        }

        /// <summary>
        /// 剧情ID
        /// </summary>
        public int StoryId { private set; get; }
        /// <summary>
        /// 类型
        /// </summary>
        public story.ConditionType Type { private set; get; }
        /// <summary>
        /// 条件
        /// </summary>
        public System.Collections.Generic.List<int> Condition { private set; get; }
        public const int __ID__ = -1393056826;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "StoryId:" + StoryId + ","
            + "Type:" + Type + ","
            + "Condition:" + StringUtil.CollectionToString(Condition) + ","
            + "}";
        }

        partial void PostInit();
    }
}
