
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config.test
{
    public sealed partial class CompositeJsonTable2 : LuBan.Runtime.BeanBase
    {
        public CompositeJsonTable2(JSONNode _buf)
        {
            { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
            { if(!_buf["y"].IsNumber) { throw new SerializationException(); }  Y = _buf["y"]; }
            PostInit();
        }

        public static CompositeJsonTable2 DeserializeCompositeJsonTable2(JSONNode _buf)
        {
            return new test.CompositeJsonTable2(_buf);
        }

        public readonly int Id;
        public readonly int Y;
        public const int __ID__ = 1566207895;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "y:" + Y + ","
            + "}";
        }

        partial void PostInit();
    }
}
