
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config.Runtime;
using SimpleJSON;

namespace Hotfix.Config.test
{
    public abstract partial class RefDynamicBase : LuBan.Runtime.BeanBase
    {
        public RefDynamicBase(JSONNode _buf)
        {
            { if(!_buf["x"].IsNumber) { throw new SerializationException(); }  X = _buf["x"]; }
            X_Ref = null;
            PostInit();
        }

        public static RefDynamicBase DeserializeRefDynamicBase(JSONNode _buf)
        {
            switch ((string)_buf["$type"])
            {
                case "RefBean": return new test.RefBean(_buf);
                default: throw new SerializationException();
            }
        }

        public readonly int X;
        public test.TestBeRef X_Ref { private set; get; }

        public virtual void ResolveRef(TablesComponent tables)
        {
            X_Ref = tables.TbTestBeRef.Get(X);
        }

        public override string ToString()
        {
            return "{ "
            + "x:" + X + ","
            + "}";
        }

        partial void PostInit();
    }
}
