
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config.test
{
    public sealed partial class Test3 : LuBan.Runtime.BeanBase
    {
        public Test3(JSONNode _buf)
        {
            { if(!_buf["x"].IsNumber) { throw new SerializationException(); }  X = _buf["x"]; }
            { if(!_buf["y"].IsNumber) { throw new SerializationException(); }  Y = _buf["y"]; }
            PostInit();
        }

        public static Test3 DeserializeTest3(JSONNode _buf)
        {
            return new test.Test3(_buf);
        }

        public readonly int X;
        public readonly int Y;
        public const int __ID__ = 638540133;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "x:" + X + ","
            + "y:" + Y + ","
            + "}";
        }

        partial void PostInit();
    }
}
