
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;


namespace Hotfix.Config.test
{
    public partial class TbDemoPrimitive : BaseDataTable<test.DemoPrimitiveTypesTable>
    {
        //private readonly System.Collections.Generic.Dictionary<int, test.DemoPrimitiveTypesTable> _dataMap;
        //private readonly System.Collections.Generic.List<test.DemoPrimitiveTypesTable> _dataList;
        private readonly System.Func<System.Threading.Tasks.Task<JSONNode>> _loadFunc;        
        public TbDemoPrimitive(System.Func<System.Threading.Tasks.Task<JSONNode>> loadFunc)
        {
            _loadFunc = loadFunc;
            //_dataMap = new System.Collections.Generic.Dictionary<int, test.DemoPrimitiveTypesTable>();
            //_dataList = new System.Collections.Generic.List<test.DemoPrimitiveTypesTable>();
        }
    
        public override async System.Threading.Tasks.Task LoadAsync()
        {
            JSONNode _json = await _loadFunc();
            //_dataMap.Clear();
            DataList.Clear();
            foreach(JSONNode _ele in _json.Children)
            {
                test.DemoPrimitiveTypesTable _v;
                { if(!_ele.IsObject) { throw new SerializationException(); }  _v = test.DemoPrimitiveTypesTable.DeserializeDemoPrimitiveTypesTable(_ele);  }
                DataList.Add(_v);                
                LongDataMaps.Add(_v.X4, _v);
                StringDataMaps.Add(_v.X4.ToString(), _v);
            }
            PostInit();
        }
    
        public void ResolveRef(TablesComponent tables)
        {
            foreach(var value in DataList)
            {
                value.ResolveRef(tables);
            }
        }
    
    
        partial void PostInit();
    }
}

