
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config.Runtime;
using SimpleJSON;

namespace Hotfix.Config.test
{
    public sealed partial class MultiRowType2 : LuBan.Runtime.BeanBase
    {
        public MultiRowType2(JSONNode _buf)
        {
            { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
            { if(!_buf["x"].IsNumber) { throw new SerializationException(); }  X = _buf["x"]; }
            { if(!_buf["y"].IsNumber) { throw new SerializationException(); }  Y = _buf["y"]; }
            PostInit();
        }

        public static MultiRowType2 DeserializeMultiRowType2(JSONNode _buf)
        {
            return new test.MultiRowType2(_buf);
        }

        public readonly int Id;
        public readonly int X;
        public readonly float Y;
        public const int __ID__ = 540474971;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "x:" + X + ","
            + "y:" + Y + ","
            + "}";
        }

        partial void PostInit();
    }
}
