
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config.Runtime;
using SimpleJSON;

namespace Hotfix.Config.test
{
    public sealed partial class Path : LuBan.Runtime.BeanBase
    {
        public Path(JSONNode _buf)
        {
            { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
            { if(!_buf["res"].IsString) { throw new SerializationException(); }  Res = _buf["res"]; }
            PostInit();
        }

        public static Path DeserializePath(JSONNode _buf)
        {
            return new test.Path(_buf);
        }

        public readonly int Id;
        public readonly string Res;
        public const int __ID__ = -1226450911;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "res:" + Res + ","
            + "}";
        }

        partial void PostInit();
    }
}
