
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config.Runtime;
using SimpleJSON;


namespace Hotfix.Config.test
{
    public partial class TbSingleton : BaseDataTable<test.DemoSingletonType>
    {
    
        private test.DemoSingletonType _data;
        public test.DemoSingletonType Data => _data;
        private readonly System.Func<System.Threading.Tasks.Task<JSONNode>> _loadFunc;
    
        public TbSingleton(System.Func<System.Threading.Tasks.Task<JSONNode>> loadFunc)
        {
            _loadFunc = loadFunc;
        }
    
        public override async System.Threading.Tasks.Task LoadAsync()
        {
            JSONNode _json = await _loadFunc();
            int n = _json.Count;
            if (n != 1) throw new SerializationException("table mode=one, but size != 1");
            { if(!_json[0].IsObject) { throw new SerializationException(); }  _data = test.DemoSingletonType.DeserializeDemoSingletonType(_json[0]);  }
        }
    
        public int Id => _data.Id;
        public string Name => _data.Name;
        public test.DemoDynamic Date => _data.Date;
    
        public void ResolveRef(TablesComponent tables)
        {
            _data.ResolveRef(tables);
        }
    
        partial void PostInit();
    }
}

