
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config.Runtime;
using SimpleJSON;

namespace Hotfix.Config.test
{
    public sealed partial class CompactString : LuBan.Runtime.BeanBase
    {
        public CompactString(JSONNode _buf)
        {
            { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
            { if(!_buf["s2"].IsString) { throw new SerializationException(); }  S2 = _buf["s2"]; }
            { if(!_buf["s3"].IsString) { throw new SerializationException(); }  S3 = _buf["s3"]; }
            PostInit();
        }

        public static CompactString DeserializeCompactString(JSONNode _buf)
        {
            return new test.CompactString(_buf);
        }

        public readonly int Id;
        public readonly string S2;
        public readonly string S3;
        public const int __ID__ = 1968089240;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "s2:" + S2 + ","
            + "s3:" + S3 + ","
            + "}";
        }

        partial void PostInit();
    }
}
