
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config.Runtime;
using SimpleJSON;


namespace Hotfix.Config.test
{
    public partial class TbItem2 : BaseDataTable<test.ItemBase>
    {
        //private readonly System.Collections.Generic.Dictionary<int, test.ItemBase> _dataMap;
        //private readonly System.Collections.Generic.List<test.ItemBase> _dataList;
        private readonly System.Func<System.Threading.Tasks.Task<JSONNode>> _loadFunc;        
        public TbItem2(System.Func<System.Threading.Tasks.Task<JSONNode>> loadFunc)
        {
            _loadFunc = loadFunc;
            //_dataMap = new System.Collections.Generic.Dictionary<int, test.ItemBase>();
            //_dataList = new System.Collections.Generic.List<test.ItemBase>();
        }
    
        public override async System.Threading.Tasks.Task LoadAsync()
        {
            JSONNode _json = await _loadFunc();
            //_dataMap.Clear();
            DataList.Clear();
            foreach(JSONNode _ele in _json.Children)
            {
                test.ItemBase _v;
                { if(!_ele.IsObject) { throw new SerializationException(); }  _v = test.ItemBase.DeserializeItemBase(_ele);  }
                DataList.Add(_v);                
                LongDataMaps.Add(_v.Id, _v);
                StringDataMaps.Add(_v.Id.ToString(), _v);
            }
            PostInit();
        }
        //public T GetOrDefaultAs<T>(int key) where T : test.ItemBase => _dataMap.TryGetValue(key, out var v) ? (T)v : null;
        //public T GetAs<T>(int key) where T : test.ItemBase => (T)_dataMap[key];
    
        public void ResolveRef(TablesComponent tables)
        {
            foreach(var value in DataList)
            {
                value.ResolveRef(tables);
            }
        }
    
    
        partial void PostInit();
    }
}

