
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config.Runtime;
using SimpleJSON;


namespace Hotfix.Config.test
{
    public partial class TbNotIndexList : BaseDataTable<test.NotIndexList>
    {
        private readonly System.Func<System.Threading.Tasks.Task<JSONNode>> _loadFunc;
    
        public TbNotIndexList(System.Func<System.Threading.Tasks.Task<JSONNode>> loadFunc)
        {
            _loadFunc = loadFunc;
        }
    
        public override async System.Threading.Tasks.Task LoadAsync()
        {
            JSONNode _json = await _loadFunc();
            DataList.Clear();
            foreach(JSONNode _ele in _json.Children)
            {
                test.NotIndexList _v;
                { if(!_ele.IsObject) { throw new SerializationException(); }  _v = test.NotIndexList.DeserializeNotIndexList(_ele);  }
                DataList.Add(_v);
            }
            PostInit();
        }
    
        //public System.Collections.Generic.List<test.NotIndexList> DataList => DataList;
    
        public void ResolveRef(TablesComponent tables)
        {
            foreach(var _v in DataList)
            {
                _v.ResolveRef(tables);
            }
        }
    
        partial void PostInit();
    }
}

