
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config.Runtime;
using SimpleJSON;

namespace Hotfix.Config.test
{
    public sealed partial class DateTimeRange : LuBan.Runtime.BeanBase
    {
        public DateTimeRange(JSONNode _buf)
        {
            { if(!_buf["start_time"].IsNumber) { throw new SerializationException(); }  StartTime = _buf["start_time"]; }
            { if(!_buf["end_time"].IsNumber) { throw new SerializationException(); }  EndTime = _buf["end_time"]; }
            PostInit();
        }

        public static DateTimeRange DeserializeDateTimeRange(JSONNode _buf)
        {
            return new test.DateTimeRange(_buf);
        }

        public readonly long StartTime;
        public readonly long EndTime;
        public const int __ID__ = 495315430;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "startTime:" + StartTime + ","
            + "endTime:" + EndTime + ","
            + "}";
        }

        partial void PostInit();
    }
}
