
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using LuBan.Runtime;
using GameFrameX.Config;
using SimpleJSON;

namespace Hotfix.Config
{
    public sealed partial class TimerParams : LuBan.Runtime.BeanBase
    {
        public TimerParams(int Level, float Number) 
        {
            this.Level = Level;
            this.Number = Number;
            PostInit();
        }

        public TimerParams(JSONNode _buf)
        {
            { if(!_buf["level"].IsNumber) { throw new SerializationException(); }  Level = _buf["level"]; }
            { if(!_buf["number"].IsNumber) { throw new SerializationException(); }  Number = _buf["number"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static TimerParams DeserializeTimerParams(JSONNode _buf)
        {
            return new TimerParams(_buf);
        }

        /// <summary>
        /// 难度级别
        /// </summary>
        public int Level { private set; get; }
        /// <summary>
        /// 天选值
        /// </summary>
        public float Number { private set; get; }
        public const int __ID__ = 1186614539;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TablesComponent tables)
        {
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "level:" + Level + ","
            + "number:" + Number + ","
            + "}";
        }

        partial void PostInit();
    }
}
