
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config.game
{ 
    /// <summary>
    /// 小游戏类型
    /// </summary>
    public enum GameType
    {
        /// <summary>
        /// 连连看
        /// </summary>
        LLK = 0,
        /// <summary>
        /// 时间挑战
        /// </summary>
        TC = 1,
        /// <summary>
        /// 连连看翻牌
        /// </summary>
        FP = 2,
    }

} 

