
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config.game
{ 
    /// <summary>
    /// 游戏难度等级
    /// </summary>
    public enum Level
    {
        /// <summary>
        /// 普通级
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 困难级
        /// </summary>
        Difficult = 1,
        /// <summary>
        /// 地狱级
        /// </summary>
        Hell = 2,
    }

} 

