
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config.instruction
{ 
    /// <summary>
    /// 指令操作类型
    /// </summary>
    [System.Flags]
    public enum OperationType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 瞬时
        /// </summary>
        Default = 1,
        /// <summary>
        /// 淡入
        /// </summary>
        FadeIn = 2,
        /// <summary>
        /// 淡出
        /// </summary>
        FadeOut = 4,
        /// <summary>
        /// 缩放
        /// </summary>
        Scale = 8,
        /// <summary>
        /// 渐变
        /// </summary>
        Gradient = 16,
        /// <summary>
        /// 溶解
        /// </summary>
        Dissolve = 32,
        /// <summary>
        /// 抖动
        /// </summary>
        Shake = 64,
        /// <summary>
        /// 移动
        /// </summary>
        Move = 128,
        /// <summary>
        /// 出现位置
        /// </summary>
        AppearanceLocation = 256,
        /// <summary>
        /// 加载资源
        /// </summary>
        Load = 512,
        /// <summary>
        /// 销毁资源
        /// </summary>
        Remove = 1024,
        /// <summary>
        /// 播放粒子
        /// </summary>
        PlayParticles = 2048,
        /// <summary>
        /// 播放Spine
        /// </summary>
        PlaySpine = 4096,
        /// <summary>
        /// 播放3D动画
        /// </summary>
        PlayAnimation = 8192,
        /// <summary>
        /// 播放Live2D
        /// </summary>
        PlayLive2D = 16384,
        /// <summary>
        /// 透明度
        /// </summary>
        Alpha = 32768,
        /// <summary>
        /// 分支
        /// </summary>
        Branch = 65536,
        /// <summary>
        /// 重置
        /// </summary>
        Reset = 131072,
        /// <summary>
        /// 描边
        /// </summary>
        Stroke = 262144,
        /// <summary>
        /// 好感度
        /// </summary>
        Likability = 524288,
        /// <summary>
        /// 章节序幕
        /// </summary>
        Chapter = 1048576,
        /// <summary>
        /// 虚化模糊
        /// </summary>
        Blurring = 2097152,
        /// <summary>
        /// 成就
        /// </summary>
        Achievement = 4194304,
    }

} 

