
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config.instruction
{ 
    /// <summary>
    /// 指令资源类型
    /// </summary>
    public enum ResourceType
    {
        /// <summary>
        /// 视频
        /// </summary>
        Video = 1,
        /// <summary>
        /// 播放声音
        /// </summary>
        Audio = 21,
        /// <summary>
        /// 背景图片
        /// </summary>
        Background = 31,
        /// <summary>
        /// 镜头
        /// </summary>
        Camera = 41,
        /// <summary>
        /// 文本
        /// </summary>
        Text = 51,
        /// <summary>
        /// 预制体
        /// </summary>
        Prefab = 61,
        /// <summary>
        /// 分支
        /// </summary>
        Branch = 71,
        /// <summary>
        /// 转场
        /// </summary>
        Transition = 81,
        /// <summary>
        /// 幕布
        /// </summary>
        Curtain = 91,
        /// <summary>
        /// 提示
        /// </summary>
        Tip = 101,
        /// <summary>
        /// 控制面板
        /// </summary>
        Control = 111,
        /// <summary>
        /// 角色
        /// </summary>
        Role = 121,
        /// <summary>
        /// 章节序幕
        /// </summary>
        Chapter = 131,
        /// <summary>
        /// 成就
        /// </summary>
        Achievement = 141,
    }

} 

