
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config.res
{ 
    public enum ShowPostion
    {
        /// <summary>
        /// 默认值
        /// </summary>
        Default = 0,
        /// <summary>
        /// 第一排第一个
        /// </summary>
        ONE = 1,
        /// <summary>
        /// 第一排第二个
        /// </summary>
        TWO = 2,
        /// <summary>
        /// 第一排第三个
        /// </summary>
        THREE = 3,
        /// <summary>
        /// 第一排第四个
        /// </summary>
        FOUR = 4,
        /// <summary>
        /// 第二排第一个
        /// </summary>
        FIVE = 5,
        /// <summary>
        /// 第二排第二个
        /// </summary>
        SIX = 6,
        /// <summary>
        /// 第二排第三个
        /// </summary>
        SEVEN = 7,
        /// <summary>
        /// 第二排第四个
        /// </summary>
        EIGHT = 8,
    }

} 

