
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config.res
{ 
    public enum TypeRes
    {
        /// <summary>
        /// 默认值
        /// </summary>
        Default = 0,
        /// <summary>
        /// 头像
        /// </summary>
        Avatar = 1,
        /// <summary>
        /// 场景
        /// </summary>
        Scene = 2,
        /// <summary>
        /// 界面
        /// </summary>
        UI = 3,
        /// <summary>
        /// 单人立绘
        /// </summary>
        SinglePainting = 4,
        /// <summary>
        /// 多人立绘
        /// </summary>
        MultiPainting = 5,
        /// <summary>
        /// 动画
        /// </summary>
        Animation = 6,
        /// <summary>
        /// 声音
        /// </summary>
        VoiceVocal = 7,
        /// <summary>
        /// 背景音乐
        /// </summary>
        VoiceBGM = 8,
        /// <summary>
        /// 场景图片
        /// </summary>
        BackGround = 9,
        /// <summary>
        /// Live2d
        /// </summary>
        Live2D = 10,
        /// <summary>
        /// 视频
        /// </summary>
        Video = 11,
    }

} 

