
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config.story
{ 
    /// <summary>
    /// 分支展示类型类型
    /// </summary>
    public enum BranchShowType
    {
        /// <summary>
        /// 垂直列表
        /// </summary>
        VerticalList = 0,
        /// <summary>
        /// 对话框
        /// </summary>
        MessageBox = 1,
        /// <summary>
        /// 横向列表
        /// </summary>
        HorizontalList = 2,
    }

} 

