
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config.story
{ 
    /// <summary>
    /// 剧情开启条件类型
    /// </summary>
    public enum ConditionType
    {
        /// <summary>
        /// 步骤序号
        /// </summary>
        Step = 0,
        /// <summary>
        /// 选项
        /// </summary>
        Option = 1,
    }

} 

