
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config.story
{ 
    public enum TransitionType
    {
        /// <summary>
        /// 默认值
        /// </summary>
        Init = 0,
        /// <summary>
        /// 读取进度时的加载
        /// </summary>
        Load = 1,
        /// <summary>
        /// 连贯剧情的加载
        /// </summary>
        Next = 2,
        /// <summary>
        /// 跳转剧情的加载
        /// </summary>
        Jump = 3,
    }

} 

