
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Config.chapter
{ 
    /// <summary>
    /// 章节名称展示位置
    /// </summary>
    public enum PositionType
    {
        Left = 0,
        Right = 1,
        Top = 2,
        Center = 3,
        Bottom = 4,
    }

} 

